### ISSUE TITLE
Be more descriptive about live boot single user mode peculiarities

### ISSUE THREAD

**Issue by grahamperrin** [helloSystem/docs#10]
From <https://hellosystem.github.io/docs/developer/boot.html#boot-into-verbose-single-user-mode>: 

> … This allows advanced users, administrators, and developers to inspect the Live system early boot process and to enter commands manually that would otherwise be executed automatically. …

Advanced users may be surprised that `exit` from single user mode does not enter multi-user mode; that [`uname(1)` and `vi(1)` are unusable](https://github.com/helloSystem/ISO/issues/75#issuecomment-753486976); and so on. 

Please consider adding a little more to the documentation. Thanks.

**Comment by probonopd** [comment]
If you boot the Live system into single-user mode, then you will be dropped into a shell in the ramdisk, and you are expected to manually enter the commands required for the Live system to continue booting which would otherwise be executed by the ramdisk automatically. Specifically, you need to enter everything below the line "Running in single-user mode" in the file overlays/ramdisk/init.sh (or variants thereof). If you just exit the shell without doing this, then the system will be unable to continue booting.

**Comment by grahamperrin** [comment]
Love the presentation. Thanks.
