### ISSUE TITLE
Contextualise the project's uses of Python

### ISSUE THREAD

**Issue by grahamperrin** [helloSystem/docs#9]
No mention of Python at https://github.com/helloSystem/hello/wiki/Welcome-and-unwelcome-technologies – consider adding a few words here. 

Re: https://github.com/helloSystem/docs/issues/8 whilst I can't seek _Python_, I do see (for example) _PyQt_ mentioned at https://hellosystem.github.io/docs/developer/applications.html

----

https://www.reddit.com/r/freebsd/comments/klvrwd/-/ghdow08/

> We'd need someone with a great conceptual understanding of … and ideally some Python skills to get it moving faster. …

https://www.reddit.com/r/freebsd/comments/kkk5ia/-/ghf4jro/?context=2

> I like the philosophy, but "written in python" is a no go from me.

From the linked [helloSystem: Three-layer UX design philosophy for Simplicity and Power …](https://medium.com/@probonopd/hellosystem-three-layer-ux-design-philosophy-for-simplicity-and-power-37c95bf58398) on Medium: 

> … many applications can be right-clicked to reveal their source code. This is because they are written in Python, … the Python example, …

**Comment by probonopd** [comment]
Some of the GUIs are written in Python with PyQt5 so that the source code is easily editable all the time. This is designed to invite (power) users to have a look at the code, start to experiment, and possibly eventually contribute. Especially when used in conjunction with the simplified `.app` bundle format and with an IDE with autocompletion, this makes for a _very_ accessible development environment with _very_ low barriers to entry. No source code to search and download, no compilers, just open the `.app` bundle and start hacking away. Tiny example applications like `Log.app` and `Calendar.app` are included that anyone should be able to understand in no time.

**Comment by probonopd** [comment]
Added a clarification to https://github.com/helloSystem/hello/wiki/Welcome-and-unwelcome-technologies.
